# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('emergencyName', models.CharField(max_length=32)),
                ('emergencyPhone', models.CharField(max_length=32)),
                ('emergencyEmail', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('disaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.Disaster')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.Shelter'),
        ),
    ]
